### ISSUE TITLE
upload.py does nothing when run

### ISSUE THREAD

**Issue by ikwyl6** [eshmu/gphotos-upload#12]
```
$ python -m venv venv
$ source venv/bin/activate
$ pip install google-auth-oauthlib
```
I followed directions to get the ```client_id``` and ```client_secret``` and inserted that into my ```client_id.json``` file.
I then try to upload a photo to an existing album:
```
$ python ./upload.py --album "EXISTING_ALBUM" pic.jpg
```
and the script just sits there and doesn't do anything. I have to hit Ctrl-CI t to exit. I try adding the ```--log``` with a log file and the file is empty after I run the same command. Any suggestions?

**Comment by ghost** [comment]
Eazy, eazy, it's possible to run upload.py without virtualenv, it should fix this problem!

**Comment by pferland** [comment]
It does not show anything when I run it without the VirtaulEnv.

But when I do run it with VirtualEnv it does show the following error:


```
[pferland@piecave gphotos-upload]$ pipenv shell
Launching subshell in virtual environment...
 . /home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/bin/activate
[pferland@piecave gphotos-upload]$  . /home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/bin/activate
(gphotos-upload) [pferland@piecave gphotos-upload]$ python upload.py --auth ./client_id.json --log ./upload.log /storage/files/Phil/Google\ Takeout/Takeout/Google\ Photos/Weekend\ in\ Niagara\ Falls/
Traceback (most recent call last):
  File "/storage/files/Phil/GitHub/gphotos-upload/upload.py", line 1, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 62, in <module>
    import google.oauth2.credentials
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/google/oauth2/credentials.py", line 42, in <module>
    from google.oauth2 import _client
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/google/oauth2/_client.py", line 35, in <module>
    from google.auth import jwt
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/google/auth/jwt.py", line 49, in <module>
    import cachetools
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/cachetools/__init__.py", line 8, in <module>
    from .cache import Cache
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/cachetools/cache.py", line 5, in <module>
    from .abc import DefaultMapping
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/cachetools/abc.py", line 7, in <module>
    class DefaultMapping(collections.MutableMapping):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by pferland** [comment]
I ran the pipenv Lock file from this Branch:  https://github.com/eshmu/gphotos-upload/blob/dependabot/pip/certifi-2022.12.7/Pipfile.lock

That got past the MutableMapping error, but is now the following even with specifying the path to the browser in upload.py

```
(gphotos-upload) [pferland@piecave gphotos-upload]$ python upload.py --auth ./client_id.json --log ./upload.log /storage/files/Phil/Google\ Takeout/Takeout/Google\ Photos/Weekend\ in\ Niagara\ Falls/
Traceback (most recent call last):
  File "/storage/files/Phil/GitHub/gphotos-upload/upload.py", line 206, in <module>
    main()
  File "/storage/files/Phil/GitHub/gphotos-upload/upload.py", line 194, in main
    session = get_authorized_session(args.auth_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/files/Phil/GitHub/gphotos-upload/upload.py", line 52, in get_authorized_session
    cred = auth(scopes)
           ^^^^^^^^^^^^
  File "/storage/files/Phil/GitHub/gphotos-upload/upload.py", line 27, in auth
    credentials = flow.run_local_server(host='localhost',
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pferland/.local/share/virtualenvs/gphotos-upload-gXXXWQmf/lib/python3.11/site-packages/google_auth_oauthlib/flow.py", line 444, in run_local_server
    webbrowser.get(browser).open(auth_url, new=1, autoraise=True)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/webbrowser.py", line 66, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
(gphotos-upload) [pferland@piecave gphotos-upload]$
```
